# Default values for cinema.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

### Mongodb values ###
community-operator:
  # define if use mongodb dependency
  enabled: true

# Cinema website values
website:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/website
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.22"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-usersAPI"
    - "http://cinema-users/api/users/"
    - "-moviesAPI"
    - "http://cinema-movies/api/movies/"
    - "-showtimesAPI"
    - "http://cinema-showtimes/api/showtimes/"
    - "-bookingsAPI"
    - "http://cinema-bookings/api/bookings/"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10 
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60 


# Cinema users values
users:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/users
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.22"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60 

# Cinema movies values
movies:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/movies
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.22"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60 

# Cinema showtimes values
showtimes:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/showtimes
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.22"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3 
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60 

# Cinema bookings values
bookings:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/bookings
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.22"

  imagePullSecrets: [ 
    name: docker-login
   ]
  

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 40
    targetMemoryUtilizationPercentage: 40 
