# Default values for cinema.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

### Mongodb values ###
community-operator:
  # define if use mongodb dependency
  enabled: true

# Cinema website values
website:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/website
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.21"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-usersAPI"
    - "http://cinema-users/api/users/"
    - "-moviesAPI"
    - "http://cinema-movies/api/movies/"
    - "-showtimesAPI"
    - "http://cinema-showtimes/api/showtimes/"
    - "-bookingsAPI"
    - "http://cinema-bookings/api/bookings/"

# Cinema users values
users:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/users
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.21"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

# Cinema movies values
movies:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/movies
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.21"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

# Cinema showtimes values
showtimes:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/showtimes
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.21"

  imagePullSecrets:  [
    name: docker-login
  ]

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"

# Cinema bookings values
bookings:
  image:
    repository: ghcr.io/autotune/microservices-docker-go-mongodb-tf/bookings
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.21"

  imagePullSecrets: [ 
    name: docker-login
   ]
  

  args:
    - "-mongoURI"
    - "mongodb://mongodb-replica-set-svc:27017/?replicaSet=mongodb-replica-set"
