apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl 
spec:
  acme:
    email: {{ .Values.zerossl_email }}
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: "Prp8UZWOJHxHgC_u1HOYwg"
      # {{ .Values.zerossl_eab_hmac_key_id }}
      keySecretRef:
        name: zerossl-eab-hmac-key 
        key: secret
      keyAlgorithm: HS256
    privateKeySecretRef:
        name: zerossl 
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: {{ .Values.zerossl_gcp_project_id }}
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-account
            key: credentials.json
    - http01:
        ingress:
          class: istio
