##########################################################################
# THIS FILE SHOULD LIVE IN .terrateam/config.yml
#
# See https://docs.terrateam.io/configuration/overview for details
##########################################################################
enabled: true
version: "1"
parallel_runs: 3
when_modified:
  file_patterns: ["**/*.tf", "**/*.tfvars"]
  autoplan: true
  autoapply: false
automerge:
  enabled: false
  delete_branch: false
checkout_strategy: merge
cost_estimation:
  enabled: true
  provider: infracost
  currency: USD
default_tf_version: latest
hooks:
  plan:
    pre: []
    post: []
  apply:
    pre: []
    post: []
dirs:
  "gcp/prod":
    tags: [gcp, prod]
    when_modified:
      file_patterns: ["gcp/prod/*.tf", "gcp/prod/*.tfvars"]
  "digitalocean":
    tags: [digitalocean]
workflows:
  - tag_query: digitalocean
    plan:
      - type: env
        name: AWS_ACCESS_KEY_ID
        cmd: ['echo', '$SPACES_ACCESS_KEY_ID']
      - type: env
        name: AWS_SECRET_ACCESS_KEY
        cmd: ['echo', '$SPACES_SECRET_ACCESS_KEY']
      - type: env
        name: TF_VAR_do_token
        cmd: ['echo', '$DIGITALOCEAN_ACCESS_TOKEN']
      - type: env
        name: TF_VAR_zerossl_eab_hmac_key
        cmd: ['echo', '$ZEROSSL_EAB_HMAC_KEY']
      - type: env
        name: TF_VAR_zerossl_eab_hmac_key_id
        cmd: ['echo', '$ZEROSSL_EAB_KEY_ID']
      - type: env
        name: TF_VAR_argocd_oidc_client_secret
        cmd: ['echo', '$ARGOCD_OIDC_SECRET']
      - type: init
      - type: plan
    apply:
      - type: env
        name: AWS_ACCESS_KEY_ID
        cmd: ['echo', '$SPACES_ACCESS_KEY_ID']
      - type: env
        name: AWS_SECRET_ACCESS_KEY
        cmd: ['echo', '$SPACES_SECRET_ACCESS_KEY']
      - type: env
        name: TF_VAR_do_token
        cmd: ['echo', '$DIGITALOCEAN_ACCESS_TOKEN']
      - type: env
        name: TF_VAR_argocd_oidc_client_secret
        cmd: ['echo', '$ARGOCD_OIDC_SECRET']
      - type: env
        name: TF_VAR_zerossl_eab_hmac_key
        cmd: ['echo', '$ZEROSSL_EAB_HMAC_KEY']
      - type: env
        name: TF_VAR_zerossl_eab_hmac_key_id
        cmd: ['echo', '$ZEROSSL_EAB_KEY_ID']
      - type: init
      - type: apply
