apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: community-operator
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb-replica-set
  targetCPUUtilizationPercentage: 40
