apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.name }} 
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.scaletargetname }}
  triggers:
  - type: cron
    metadata:
      timezone: America/Chicago
      start: 0 6 * * *
      end: 0 13 * * *
      desiredReplicas: "4" 
