name: release

on:
  push:
    tags:
      - "v*"

env:
  USERS_IMAGE_NAME: "cinema-users"
  MOVIES_IMAGE_NAME: "cinema-movies"
  SHOWTIMES_IMAGE_NAME: "cinema-showtimes"
  BOOKINGS_IMAGE_NAME: "cinema-bookings"
  WEBSITE_IMAGE_NAME: "cinema-website"

jobs:
  multi-registries:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: GitHub Package Registry - Users
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.PACKAGE_REGISTRY_PAT }}
          build_file: Dockerfile
          path: ./users/
          image: autotune/microservices-docker-go-mongodb-tf/users
          tag: ${{ steps.slug.outputs.get_version }}
          cache: true
          cache_registry: cache
      - name: GitHub Package Registry - Movies
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.PACKAGE_REGISTRY_PAT }}
          build_file: Dockerfile
          path: ./movies/
          image: autotune/microservices-docker-go-mongodb-tf/movies
          tag: ${{ steps.slug.outputs.get_version }}
          cache: true
          cache_registry: cache

        

        
